version: '3'

services:
  app:
    build: ./php
    volumes:
      - ./src:/var/www/html/integrador
    working_dir: /var/www/html/integrador
    networks:
      - app-network

  #Nginx Service
  webserver:
    build: ./nginx
    container_name: webserver
    restart: always
    depends_on:
      - app
    ports:
      - 8008:80
    volumes:
      - ./src:/var/www/html/integrador
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
